/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.ajudeaqui.view;

/**
 *
 * @author jaime
 */
public class PrincipalInstituicaoUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalInstituicaoUI
     */
    public PrincipalInstituicaoUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipal = new javax.swing.JTabbedPane();
        panelInstituicao = new javax.swing.JPanel();
        lblDadosInstituicao = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblRazaoSocial = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblSite = new javax.swing.JLabel();
        lblResponsavel = new javax.swing.JLabel();
        lblObservacoes = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtRazaoSocial = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtSite = new javax.swing.JTextField();
        txtResponsavel = new javax.swing.JTextField();
        scrollpaneObservacoes = new javax.swing.JScrollPane();
        atxtObservacoes = new javax.swing.JTextArea();
        btnSalvarDadosInstituicao = new javax.swing.JButton();
        panelVoluntarios = new javax.swing.JPanel();
        panelFiltroVoluntarios = new javax.swing.JPanel();
        lblNomeFiltroVoluntarios = new javax.swing.JLabel();
        lblEmailFiltroVoluntarios = new javax.swing.JLabel();
        txtNomeFiltroVoluntarios = new javax.swing.JTextField();
        txtEmailFiltroVoluntarios = new javax.swing.JTextField();
        btnPesquisarFiltroVoluntarios = new javax.swing.JButton();
        scrollpaneVoluntarios = new javax.swing.JScrollPane();
        tableVoluntarios = new javax.swing.JTable();
        panelAviso = new javax.swing.JPanel();
        panelCadAviso = new javax.swing.JPanel();
        lblTituloCadAviso = new javax.swing.JLabel();
        txtTituloCadAviso = new javax.swing.JTextField();
        lblDescricaoCadAviso = new javax.swing.JLabel();
        scrollpaneDescricaoCadAviso = new javax.swing.JScrollPane();
        atxtDescricaoCadAviso = new javax.swing.JTextArea();
        btnSalvarAnuncioCadAviso = new javax.swing.JButton();
        panelAvisosPublicados = new javax.swing.JPanel();
        scrollpaneAvisosPublicados = new javax.swing.JScrollPane();
        tableAvisosPublicados = new javax.swing.JTable();
        lblFiltroTituloAvisosPublicados = new javax.swing.JLabel();
        txtFiltroTituloAvisosPublicados = new javax.swing.JTextField();
        btnPesquisarAvisosPublicados = new javax.swing.JButton();
        panelAnuncio = new javax.swing.JPanel();
        panelAnunciosPublicados = new javax.swing.JPanel();
        scrollpaneAnunciosPublicados = new javax.swing.JScrollPane();
        tableAnunciosPublicados1 = new javax.swing.JTable();
        btnPesquisarAnunciosPublicados = new javax.swing.JButton();
        lblFiltroTituloAnunciosPublicados = new javax.swing.JLabel();
        txtFiltroTituloAnunciosPublicados = new javax.swing.JTextField();
        panelCadAnuncio = new javax.swing.JPanel();
        lblTituloCadAnuncio = new javax.swing.JLabel();
        cmbTipoCadAnuncio = new javax.swing.JComboBox();
        lblTipoCadAnuncio = new javax.swing.JLabel();
        spinnerVagasCadAnuncio = new javax.swing.JSpinner();
        lblVagasCadAnuncio = new javax.swing.JLabel();
        txtTituloCadAnuncio = new javax.swing.JTextField();
        lblDescricaoCadAnuncio = new javax.swing.JLabel();
        scrollpaneDescricaoCadAnuncio = new javax.swing.JScrollPane();
        atxtDescricaoCadAnuncio = new javax.swing.JTextArea();
        btnSalvarCadAnuncio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(":: Portal do Voluntário Ajude Aqui ::");
        setMaximumSize(new java.awt.Dimension(1010, 730));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("frameInstituicao"); // NOI18N

        menuPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuPrincipal.setMaximumSize(new java.awt.Dimension(1010, 730));
        menuPrincipal.setMinimumSize(new java.awt.Dimension(800, 600));
        menuPrincipal.setPreferredSize(new java.awt.Dimension(1010, 730));

        panelInstituicao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDadosInstituicao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDadosInstituicao.setText("Dados da Instituição");

        lblNome.setText("Nome:");

        lblRazaoSocial.setText("Razão Social:");

        lblCnpj.setText("CNPJ:");

        lblEmail.setText("Email:");

        lblTelefone.setText("Telefone:");

        lblEndereco.setText("Endereço:");

        lblSite.setText("Site:");

        lblResponsavel.setText("Responsável:");

        lblObservacoes.setText("Observações:");

        atxtObservacoes.setColumns(20);
        atxtObservacoes.setRows(5);
        scrollpaneObservacoes.setViewportView(atxtObservacoes);

        btnSalvarDadosInstituicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar_16x16.png"))); // NOI18N
        btnSalvarDadosInstituicao.setText("Salvar");

        javax.swing.GroupLayout panelInstituicaoLayout = new javax.swing.GroupLayout(panelInstituicao);
        panelInstituicao.setLayout(panelInstituicaoLayout);
        panelInstituicaoLayout.setHorizontalGroup(
            panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstituicaoLayout.createSequentialGroup()
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblDadosInstituicao))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCnpj))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEmail))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInstituicaoLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInstituicaoLayout.createSequentialGroup()
                                            .addComponent(lblRazaoSocial)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInstituicaoLayout.createSequentialGroup()
                                            .addComponent(lblTelefone)
                                            .addGap(38, 38, 38))))
                                .addGroup(panelInstituicaoLayout.createSequentialGroup()
                                    .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelInstituicaoLayout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(lblNome))
                                        .addGroup(panelInstituicaoLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(lblEndereco)))
                                    .addGap(35, 35, 35)))
                            .addGroup(panelInstituicaoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSite)
                                    .addComponent(lblResponsavel))
                                .addGap(19, 19, 19)))
                        .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalvarDadosInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInstituicaoLayout.createSequentialGroup()
                                .addComponent(lblObservacoes)
                                .addGap(18, 18, 18)
                                .addComponent(scrollpaneObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(553, 553, 553))
        );
        panelInstituicaoLayout.setVerticalGroup(
            panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstituicaoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblDadosInstituicao)
                .addGap(9, 9, 9)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaoSocial)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCnpj)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSite)
                    .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResponsavel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservacoes)
                    .addComponent(scrollpaneObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvarDadosInstituicao)
                .addContainerGap())
        );

        menuPrincipal.addTab("Instituição", new javax.swing.ImageIcon(getClass().getResource("/img/home_16x16.png.png")), panelInstituicao); // NOI18N

        panelVoluntarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelFiltroVoluntarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro de Pesquisa"));

        lblNomeFiltroVoluntarios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblNomeFiltroVoluntarios.setText("Nome:");

        lblEmailFiltroVoluntarios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblEmailFiltroVoluntarios.setText("Email:");

        btnPesquisarFiltroVoluntarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa_16x16.png"))); // NOI18N
        btnPesquisarFiltroVoluntarios.setText("Pesquisar");

        javax.swing.GroupLayout panelFiltroVoluntariosLayout = new javax.swing.GroupLayout(panelFiltroVoluntarios);
        panelFiltroVoluntarios.setLayout(panelFiltroVoluntariosLayout);
        panelFiltroVoluntariosLayout.setHorizontalGroup(
            panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeFiltroVoluntarios)
                    .addComponent(lblEmailFiltroVoluntarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeFiltroVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailFiltroVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisarFiltroVoluntarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFiltroVoluntariosLayout.setVerticalGroup(
            panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFiltroVoluntariosLayout.createSequentialGroup()
                            .addComponent(txtNomeFiltroVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtEmailFiltroVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFiltroVoluntariosLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarFiltroVoluntarios)))
                    .addGroup(panelFiltroVoluntariosLayout.createSequentialGroup()
                        .addComponent(lblNomeFiltroVoluntarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmailFiltroVoluntarios)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableVoluntarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data Nascimento", "Endereço", "Celular", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVoluntarios.setAutoscrolls(false);
        scrollpaneVoluntarios.setViewportView(tableVoluntarios);

        javax.swing.GroupLayout panelVoluntariosLayout = new javax.swing.GroupLayout(panelVoluntarios);
        panelVoluntarios.setLayout(panelVoluntariosLayout);
        panelVoluntariosLayout.setHorizontalGroup(
            panelVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpaneVoluntarios, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                    .addComponent(panelFiltroVoluntarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelVoluntariosLayout.setVerticalGroup(
            panelVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFiltroVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollpaneVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuPrincipal.addTab("Voluntários", new javax.swing.ImageIcon(getClass().getResource("/img/usuarios_16x16.png")), panelVoluntarios); // NOI18N

        panelAviso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelCadAviso.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Avisos"));

        lblTituloCadAviso.setText("Título:");

        lblDescricaoCadAviso.setText("Descrição:");

        atxtDescricaoCadAviso.setColumns(20);
        atxtDescricaoCadAviso.setRows(5);
        scrollpaneDescricaoCadAviso.setViewportView(atxtDescricaoCadAviso);

        btnSalvarAnuncioCadAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar_16x16.png"))); // NOI18N
        btnSalvarAnuncioCadAviso.setText("Salvar");

        javax.swing.GroupLayout panelCadAvisoLayout = new javax.swing.GroupLayout(panelCadAviso);
        panelCadAviso.setLayout(panelCadAvisoLayout);
        panelCadAvisoLayout.setHorizontalGroup(
            panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadAvisoLayout.createSequentialGroup()
                .addGroup(panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCadAvisoLayout.createSequentialGroup()
                        .addComponent(lblTituloCadAviso)
                        .addGap(30, 30, 30)
                        .addComponent(txtTituloCadAviso))
                    .addGroup(panelCadAvisoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGap(247, 247, 247)
                        .addComponent(btnSalvarAnuncioCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadAvisoLayout.createSequentialGroup()
                        .addComponent(lblDescricaoCadAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollpaneDescricaoCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCadAvisoLayout.setVerticalGroup(
            panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadAvisoLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCadAviso)
                    .addComponent(txtTituloCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricaoCadAviso)
                    .addComponent(scrollpaneDescricaoCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarAnuncioCadAviso)
                .addGap(55, 55, 55))
        );

        panelAvisosPublicados.setBorder(javax.swing.BorderFactory.createTitledBorder("Avisos Publicados"));

        tableAvisosPublicados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableAvisosPublicados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Teste", "Teste"},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Título", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAvisosPublicados.setRowHeight(30);
        scrollpaneAvisosPublicados.setViewportView(tableAvisosPublicados);

        lblFiltroTituloAvisosPublicados.setText("Título:");

        btnPesquisarAvisosPublicados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa_16x16.png"))); // NOI18N
        btnPesquisarAvisosPublicados.setText("Pesquisar");

        javax.swing.GroupLayout panelAvisosPublicadosLayout = new javax.swing.GroupLayout(panelAvisosPublicados);
        panelAvisosPublicados.setLayout(panelAvisosPublicadosLayout);
        panelAvisosPublicadosLayout.setHorizontalGroup(
            panelAvisosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvisosPublicadosLayout.createSequentialGroup()
                .addGroup(panelAvisosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAvisosPublicadosLayout.createSequentialGroup()
                        .addComponent(lblFiltroTituloAvisosPublicados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltroTituloAvisosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarAvisosPublicados))
                    .addComponent(scrollpaneAvisosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelAvisosPublicadosLayout.setVerticalGroup(
            panelAvisosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAvisosPublicadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAvisosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltroTituloAvisosPublicados)
                    .addComponent(txtFiltroTituloAvisosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarAvisosPublicados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpaneAvisosPublicados, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAvisoLayout = new javax.swing.GroupLayout(panelAviso);
        panelAviso.setLayout(panelAvisoLayout);
        panelAvisoLayout.setHorizontalGroup(
            panelAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAvisosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, Short.MAX_VALUE)
            .addComponent(panelCadAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAvisoLayout.setVerticalGroup(
            panelAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvisoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCadAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAvisosPublicados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPrincipal.addTab("Aviso", new javax.swing.ImageIcon(getClass().getResource("/img/journal_16x16.png")), panelAviso); // NOI18N

        panelAnuncio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelAnunciosPublicados.setBorder(javax.swing.BorderFactory.createTitledBorder("Anúncios Publicados"));

        tableAnunciosPublicados1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título", "Vagas Disponíveis", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAnunciosPublicados1.setRowHeight(30);
        scrollpaneAnunciosPublicados.setViewportView(tableAnunciosPublicados1);

        btnPesquisarAnunciosPublicados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa_16x16.png"))); // NOI18N
        btnPesquisarAnunciosPublicados.setText("Pesquisar");

        lblFiltroTituloAnunciosPublicados.setText("Título:");

        javax.swing.GroupLayout panelAnunciosPublicadosLayout = new javax.swing.GroupLayout(panelAnunciosPublicados);
        panelAnunciosPublicados.setLayout(panelAnunciosPublicadosLayout);
        panelAnunciosPublicadosLayout.setHorizontalGroup(
            panelAnunciosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnunciosPublicadosLayout.createSequentialGroup()
                .addComponent(lblFiltroTituloAnunciosPublicados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltroTituloAnunciosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarAnunciosPublicados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(scrollpaneAnunciosPublicados, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );
        panelAnunciosPublicadosLayout.setVerticalGroup(
            panelAnunciosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnunciosPublicadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAnunciosPublicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltroTituloAnunciosPublicados)
                    .addComponent(txtFiltroTituloAnunciosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarAnunciosPublicados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpaneAnunciosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelCadAnuncio.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Anuncios"));

        lblTituloCadAnuncio.setText("Título:");

        cmbTipoCadAnuncio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Anúnciar Vaga", "Aviso" }));

        lblTipoCadAnuncio.setText("Tipo:");

        lblVagasCadAnuncio.setText("Vagas:");

        lblDescricaoCadAnuncio.setText("Descrição:");

        atxtDescricaoCadAnuncio.setColumns(20);
        atxtDescricaoCadAnuncio.setRows(5);
        scrollpaneDescricaoCadAnuncio.setViewportView(atxtDescricaoCadAnuncio);

        btnSalvarCadAnuncio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar_16x16.png"))); // NOI18N
        btnSalvarCadAnuncio.setText("Salvar");

        javax.swing.GroupLayout panelCadAnuncioLayout = new javax.swing.GroupLayout(panelCadAnuncio);
        panelCadAnuncio.setLayout(panelCadAnuncioLayout);
        panelCadAnuncioLayout.setHorizontalGroup(
            panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadAnuncioLayout.createSequentialGroup()
                .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVagasCadAnuncio)
                    .addComponent(lblTipoCadAnuncio)
                    .addComponent(lblTituloCadAnuncio)
                    .addComponent(lblDescricaoCadAnuncio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTipoCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerVagasCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCadAnuncioLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnSalvarCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollpaneDescricaoCadAnuncio)
                    .addComponent(txtTituloCadAnuncio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCadAnuncioLayout.setVerticalGroup(
            panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadAnuncioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCadAnuncio)
                    .addComponent(txtTituloCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoCadAnuncio)
                    .addComponent(cmbTipoCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVagasCadAnuncio)
                    .addComponent(spinnerVagasCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricaoCadAnuncio)
                    .addComponent(scrollpaneDescricaoCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarCadAnuncio)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout panelAnuncioLayout = new javax.swing.GroupLayout(panelAnuncio);
        panelAnuncio.setLayout(panelAnuncioLayout);
        panelAnuncioLayout.setHorizontalGroup(
            panelAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnuncioLayout.createSequentialGroup()
                .addGroup(panelAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAnunciosPublicados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCadAnuncio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAnuncioLayout.setVerticalGroup(
            panelAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnuncioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCadAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAnunciosPublicados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        menuPrincipal.addTab("Anúncio", new javax.swing.ImageIcon(getClass().getResource("/img/aviso_16x16.png")), panelAnuncio); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        menuPrincipal.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalInstituicaoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxtDescricaoCadAnuncio;
    private javax.swing.JTextArea atxtDescricaoCadAviso;
    private javax.swing.JTextArea atxtObservacoes;
    private javax.swing.JButton btnPesquisarAnunciosPublicados;
    private javax.swing.JButton btnPesquisarAvisosPublicados;
    private javax.swing.JButton btnPesquisarFiltroVoluntarios;
    private javax.swing.JButton btnSalvarAnuncioCadAviso;
    private javax.swing.JButton btnSalvarCadAnuncio;
    private javax.swing.JButton btnSalvarDadosInstituicao;
    private javax.swing.JComboBox cmbTipoCadAnuncio;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblDadosInstituicao;
    private javax.swing.JLabel lblDescricaoCadAnuncio;
    private javax.swing.JLabel lblDescricaoCadAviso;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailFiltroVoluntarios;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFiltroTituloAnunciosPublicados;
    private javax.swing.JLabel lblFiltroTituloAvisosPublicados;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeFiltroVoluntarios;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblResponsavel;
    private javax.swing.JLabel lblSite;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipoCadAnuncio;
    private javax.swing.JLabel lblTituloCadAnuncio;
    private javax.swing.JLabel lblTituloCadAviso;
    private javax.swing.JLabel lblVagasCadAnuncio;
    private javax.swing.JTabbedPane menuPrincipal;
    private javax.swing.JPanel panelAnuncio;
    private javax.swing.JPanel panelAnunciosPublicados;
    private javax.swing.JPanel panelAviso;
    private javax.swing.JPanel panelAvisosPublicados;
    private javax.swing.JPanel panelCadAnuncio;
    private javax.swing.JPanel panelCadAviso;
    private javax.swing.JPanel panelFiltroVoluntarios;
    private javax.swing.JPanel panelInstituicao;
    private javax.swing.JPanel panelVoluntarios;
    private javax.swing.JScrollPane scrollpaneAnunciosPublicados;
    private javax.swing.JScrollPane scrollpaneAvisosPublicados;
    private javax.swing.JScrollPane scrollpaneDescricaoCadAnuncio;
    private javax.swing.JScrollPane scrollpaneDescricaoCadAviso;
    private javax.swing.JScrollPane scrollpaneObservacoes;
    private javax.swing.JScrollPane scrollpaneVoluntarios;
    private javax.swing.JSpinner spinnerVagasCadAnuncio;
    private javax.swing.JTable tableAnunciosPublicados1;
    private javax.swing.JTable tableAvisosPublicados;
    private javax.swing.JTable tableVoluntarios;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailFiltroVoluntarios;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFiltroTituloAnunciosPublicados;
    private javax.swing.JTextField txtFiltroTituloAvisosPublicados;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeFiltroVoluntarios;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTituloCadAnuncio;
    private javax.swing.JTextField txtTituloCadAviso;
    // End of variables declaration//GEN-END:variables
}
