/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.ajudeaqui.view;

/**
 *
 * @author jaime
 */
public class PrincipalInstituicaoUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalInstituicaoUI
     */
    public PrincipalInstituicaoUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipal = new javax.swing.JTabbedPane();
        panelInstituicao = new javax.swing.JPanel();
        lblDadosInstituicao = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblRazaoSocial = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblSite = new javax.swing.JLabel();
        lblResponsavel = new javax.swing.JLabel();
        lblObservacoes = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtRazaoSocial = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtSite = new javax.swing.JTextField();
        txtResponsavel = new javax.swing.JTextField();
        scrollPaneObservacoes = new javax.swing.JScrollPane();
        atxtObservacoes = new javax.swing.JTextArea();
        panelVoluntarios = new javax.swing.JPanel();
        panelFiltroVoluntarios = new javax.swing.JPanel();
        lblTituloFiltroVagas = new javax.swing.JLabel();
        lblInstituicaoFiltroVagas = new javax.swing.JLabel();
        txtTituloFiltroVagas = new javax.swing.JTextField();
        txtTituloFiltroVagas1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVagas = new javax.swing.JTable();
        panelAnunciar = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        scrollPaneDescricao = new javax.swing.JScrollPane();
        atxtDescricao = new javax.swing.JTextArea();
        lblVagas = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        spinnerVagas = new javax.swing.JSpinner();
        btnSalvarAnuncio = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        lblAnunciosAvisos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(":: Portal do Voluntário Ajude Aqui ::");
        setMaximumSize(new java.awt.Dimension(1010, 730));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("frameInstituicao"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1010, 730));

        menuPrincipal.setMaximumSize(new java.awt.Dimension(1010, 730));
        menuPrincipal.setMinimumSize(new java.awt.Dimension(800, 600));
        menuPrincipal.setPreferredSize(new java.awt.Dimension(1010, 730));

        lblDadosInstituicao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDadosInstituicao.setForeground(new java.awt.Color(0, 0, 0));
        lblDadosInstituicao.setText("Dados da Instituição");

        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome:");

        lblRazaoSocial.setForeground(new java.awt.Color(0, 0, 0));
        lblRazaoSocial.setText("Razão Social:");

        lblCnpj.setForeground(new java.awt.Color(0, 0, 0));
        lblCnpj.setText("CNPJ:");

        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("Email:");

        lblTelefone.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefone.setText("Telefone:");

        lblEndereco.setForeground(new java.awt.Color(0, 0, 0));
        lblEndereco.setText("Endereço:");

        lblSite.setForeground(new java.awt.Color(0, 0, 0));
        lblSite.setText("Site:");

        lblResponsavel.setForeground(new java.awt.Color(0, 0, 0));
        lblResponsavel.setText("Responsável:");

        lblObservacoes.setForeground(new java.awt.Color(0, 0, 0));
        lblObservacoes.setText("Observações:");

        atxtObservacoes.setColumns(20);
        atxtObservacoes.setRows(5);
        scrollPaneObservacoes.setViewportView(atxtObservacoes);

        javax.swing.GroupLayout panelInstituicaoLayout = new javax.swing.GroupLayout(panelInstituicao);
        panelInstituicao.setLayout(panelInstituicaoLayout);
        panelInstituicaoLayout.setHorizontalGroup(
            panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstituicaoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDadosInstituicao)
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(68, 68, 68)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addComponent(lblRazaoSocial)
                        .addGap(18, 18, 18)
                        .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addComponent(lblCnpj)
                        .addGap(76, 76, 76)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addGap(71, 71, 71)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addGap(46, 46, 46)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addComponent(lblEndereco)
                        .addGap(42, 42, 42)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addComponent(lblSite)
                        .addGap(80, 80, 80)
                        .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addComponent(lblResponsavel)
                        .addGap(18, 18, 18)
                        .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addComponent(lblObservacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollPaneObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelInstituicaoLayout.setVerticalGroup(
            panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstituicaoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblDadosInstituicao)
                .addGap(8, 8, 8)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblNome))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblRazaoSocial))
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblCnpj))
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblEmail))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblTelefone))
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndereco))
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSite)))
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblResponsavel)))
                .addGroup(panelInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(scrollPaneObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInstituicaoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblObservacoes))))
        );

        menuPrincipal.addTab("Instituição", new javax.swing.ImageIcon(getClass().getResource("/img/home_16x16.png.png")), panelInstituicao); // NOI18N

        panelFiltroVoluntarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro de Pesquisa"));

        lblTituloFiltroVagas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblTituloFiltroVagas.setText("Nome:");

        lblInstituicaoFiltroVagas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblInstituicaoFiltroVagas.setText("Email:");

        javax.swing.GroupLayout panelFiltroVoluntariosLayout = new javax.swing.GroupLayout(panelFiltroVoluntarios);
        panelFiltroVoluntarios.setLayout(panelFiltroVoluntariosLayout);
        panelFiltroVoluntariosLayout.setHorizontalGroup(
            panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloFiltroVagas)
                    .addComponent(lblInstituicaoFiltroVagas))
                .addGap(48, 48, 48)
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTituloFiltroVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTituloFiltroVagas1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFiltroVoluntariosLayout.setVerticalGroup(
            panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloFiltroVagas)
                    .addComponent(txtTituloFiltroVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFiltroVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstituicaoFiltroVagas)
                    .addComponent(txtTituloFiltroVagas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tableVagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data Nascimento", "Endereço", "Celular", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVagas.setAutoscrolls(false);
        jScrollPane1.setViewportView(tableVagas);

        javax.swing.GroupLayout panelVoluntariosLayout = new javax.swing.GroupLayout(panelVoluntarios);
        panelVoluntarios.setLayout(panelVoluntariosLayout);
        panelVoluntariosLayout.setHorizontalGroup(
            panelVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                    .addComponent(panelFiltroVoluntarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelVoluntariosLayout.setVerticalGroup(
            panelVoluntariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVoluntariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFiltroVoluntarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPrincipal.addTab("Voluntários", new javax.swing.ImageIcon(getClass().getResource("/img/usuarios_16x16.png")), panelVoluntarios); // NOI18N

        lblTitulo.setText("Título:");

        atxtDescricao.setColumns(20);
        atxtDescricao.setRows(5);
        scrollPaneDescricao.setViewportView(atxtDescricao);

        lblVagas.setText("Vagas:");

        lblDescricao.setText("Descrição:");

        btnSalvarAnuncio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar_16x16.png"))); // NOI18N
        btnSalvarAnuncio.setText("Salvar");

        lblTipo.setText("Tipo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Anúnciar Vaga", "Aviso" }));

        lblAnunciosAvisos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAnunciosAvisos.setText("Anuncios e Avisos");

        javax.swing.GroupLayout panelAnunciarLayout = new javax.swing.GroupLayout(panelAnunciar);
        panelAnunciar.setLayout(panelAnunciarLayout);
        panelAnunciarLayout.setHorizontalGroup(
            panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnunciarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAnunciarLayout.createSequentialGroup()
                        .addGroup(panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAnunciarLayout.createSequentialGroup()
                                .addGroup(panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitulo)
                                    .addComponent(lblVagas))
                                .addGap(37, 37, 37)
                                .addGroup(panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblTipo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAnunciarLayout.createSequentialGroup()
                        .addGroup(panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalvarAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAnunciosAvisos)
                                .addGroup(panelAnunciarLayout.createSequentialGroup()
                                    .addComponent(lblDescricao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(scrollPaneDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnunciarLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(777, 777, 777))
        );
        panelAnunciarLayout.setVerticalGroup(
            panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnunciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnunciosAvisos)
                .addGap(18, 18, 18)
                .addGroup(panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVagas)
                    .addComponent(spinnerVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAnunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(scrollPaneDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvarAnuncio)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        menuPrincipal.addTab("Anunciar", new javax.swing.ImageIcon(getClass().getResource("/img/journal_16x16.png")), panelAnunciar); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuPrincipal.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalInstituicaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalInstituicaoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxtDescricao;
    private javax.swing.JTextArea atxtObservacoes;
    private javax.swing.JButton btnSalvarAnuncio;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnunciosAvisos;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblDadosInstituicao;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblInstituicaoFiltroVagas;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblResponsavel;
    private javax.swing.JLabel lblSite;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloFiltroVagas;
    private javax.swing.JLabel lblVagas;
    private javax.swing.JTabbedPane menuPrincipal;
    private javax.swing.JPanel panelAnunciar;
    private javax.swing.JPanel panelFiltroVoluntarios;
    private javax.swing.JPanel panelInstituicao;
    private javax.swing.JPanel panelVoluntarios;
    private javax.swing.JScrollPane scrollPaneDescricao;
    private javax.swing.JScrollPane scrollPaneObservacoes;
    private javax.swing.JSpinner spinnerVagas;
    private javax.swing.JTable tableVagas;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTituloFiltroVagas;
    private javax.swing.JTextField txtTituloFiltroVagas1;
    // End of variables declaration//GEN-END:variables
}
